# Generated by Django 3.0.4 on 2020-03-19 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Color'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Size'),
            preserve_default=False,
        ),
    ]
