# Generated by Django 3.0.4 on 2020-03-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200320_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.ManyToManyField(to='product.Color'),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.ManyToManyField(to='product.Size'),
        ),
    ]
