# Generated by Django 3.0.4 on 2020-03-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200320_0245'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('color', 'size')},
        ),
    ]
