# Generated by Django 3.0.4 on 2020-03-19 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200320_0251'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('color', 'size', 'product')},
        ),
    ]
