# Generated by Django 3.0.4 on 2020-03-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200320_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
