# Generated by Django 3.0.4 on 2020-03-22 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200322_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='product.Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='product.Size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock_total',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
