# Generated by Django 3.0.4 on 2020-03-22 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200323_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bag_purchase_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gsm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='marketing_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_total',
        ),
        migrations.RemoveField(
            model_name='product',
            name='transport_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vat',
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsm', models.CharField(choices=[('25', 25), ('30', 30), ('40', 40), ('50', 50), ('60', 60), ('70', 70), ('80', 80), ('90', 90), ('100', 100), ('110', 110)], max_length=4)),
                ('bag_purchase_price', models.FloatField(default=0.0)),
                ('marketing_cost', models.FloatField(default=0.0)),
                ('vat', models.FloatField(default=0.0)),
                ('profit', models.FloatField(default=0.0)),
                ('transport_cost', models.FloatField(default=0.0)),
                ('stock_total', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='product.Color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='product.Product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='product.Size')),
            ],
            options={
                'unique_together': {('color', 'size', 'product', 'gsm', 'category')},
            },
        ),
    ]
