# Generated by Django 3.0.4 on 2020-04-03 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='product_variant',
        ),
        migrations.CreateModel(
            name='SupplerTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_suplied', models.IntegerField()),
                ('product_variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductVariant')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Supplier')),
            ],
        ),
    ]
