# Generated by Django 3.0.4 on 2020-04-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20200403_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplertransaction',
            old_name='total_suplied',
            new_name='total_supplied',
        ),
    ]
