# Generated by Django 3.0.4 on 2020-04-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20200403_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
