# Generated by Django 3.0.4 on 2020-04-04 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20200404_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliertransaction',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='suppliertransaction',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variant', to='product.Product'),
        ),
    ]
