# Generated by Django 3.0.4 on 2020-04-04 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20200404_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliertransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='product_variantiiii', to='product.ProductVariant'),
        ),
    ]
