# Generated by Django 3.0.4 on 2020-04-04 18:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20200404_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliertransaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='suppliertransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variant', to='product.ProductVariant'),
        ),
    ]
