# Generated by Django 3.0.4 on 2020-04-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_auto_20200406_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
    ]
