# Generated by Django 3.0.4 on 2020-04-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_productvariant_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_total',
            field=models.FloatField(default=0),
        ),
    ]
