# Generated by Django 3.0.4 on 2020-04-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_order_paid_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='discount_peice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='printing_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
