# Generated by Django 3.0.4 on 2020-04-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_auto_20200407_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='discount_peice',
            new_name='discount_min_purchase',
        ),
    ]
